//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketFlix.Commons.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIENTO
    {
        public int IDAsiento { get; set; }
        public string Orden { get; set; }
        public bool Disponiblidad { get; set; }
    
        public virtual HORARIO HORARIO { get; set; }
    }
}
