//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketFlix.Commons.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public int IDHorario { get; set; }
        public string Horario { get; set; }
    
        public virtual SALA SALA { get; set; }
    }
}
