//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketFlix.Commons.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public INVENTARIO()
        {
            this.PRODUCTOes = new HashSet<PRODUCTO>();
        }
    
        public int IDInventario { get; set; }
        public int Cantidad { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTOes { get; set; }
    }
}
