//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketFlix.Commons.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int IDProducto { get; set; }
        public string Nombre { get; set; }
        public int Costo { get; set; }
    
        public virtual INVENTARIO INVENTARIO { get; set; }
    }
}
