//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketFlix.Commons.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALA
    {
        public SALA()
        {
            this.HORARIOs = new HashSet<HORARIO>();
        }
    
        public int IDSala { get; set; }
        public string Película { get; set; }
    
        public virtual ICollection<HORARIO> HORARIOs { get; set; }
    }
}
