//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketFlix.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TicketFlix.Commons.Entities;
    
    public partial class TicketFlixEntities : DbContext
    {
        public TicketFlixEntities()
            : base("name=TicketFlixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ASIENTO> ASIENTOes { get; set; }
        public DbSet<HORARIO> HORARIOs { get; set; }
        public DbSet<INVENTARIO> INVENTARIOs { get; set; }
        public DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public DbSet<SALA> SALAs { get; set; }
    }
}
